# Generated by Django 4.0.4 on 2022-04-26 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0003_filesadmin_downloadooption'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesadmin',
            name='discription',
            field=models.CharField(default='', max_length=3000),
            preserve_default=False,
        ),
    ]
