# Generated by Django 4.0.4 on 2022-04-26 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0004_filesadmin_discription'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesadmin',
            name='imag',
            field=models.ImageField(default='', height_field=50, upload_to='media'),
            preserve_default=False,
        ),
    ]
