# Generated by Django 4.0.4 on 2022-04-26 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0005_filesadmin_imag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesadmin',
            name='discription',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='filesadmin',
            name='imag',
            field=models.ImageField(upload_to='media'),
        ),
    ]
